# Generated by Django 2.2.12 on 2020-07-24 21:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_record', '0003_auto_20200724_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerpatient',
            name='refference',
            field=models.CharField(default=datetime.datetime(2020, 7, 24, 21, 24, 30, 675394, tzinfo=utc), max_length=200),
        ),
    ]
