# Generated by Django 2.2.12 on 2020-07-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='status',
            field=models.CharField(default='available', max_length=200),
        ),
    ]
