# Generated by Django 2.2.12 on 2020-07-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_specimen_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='RBC',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='hemoglobin',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='specimen_name',
        ),
    ]
