# Generated by Django 2.2.12 on 2020-07-26 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0002_specimen_status'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecimenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reff', models.CharField(default=1595790152, max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Specimen')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
