# Generated by Django 2.2.12 on 2020-07-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20200726_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimendata',
            name='pathologist',
            field=models.CharField(default='no', max_length=200),
        ),
        migrations.AddField(
            model_name='specimendata',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='specimendata',
            name='reff',
            field=models.CharField(default=1595877393657, max_length=200),
        ),
    ]
