# Generated by Django 2.2.12 on 2020-07-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20200729_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimendata',
            name='reff',
            field=models.CharField(default=1596026419582, max_length=200),
        ),
        migrations.AlterField(
            model_name='specimendata',
            name='temperature',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='specimendata',
            name='weight',
            field=models.CharField(max_length=200),
        ),
    ]
