# Generated by Django 2.2.12 on 2020-07-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20200729_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimendata',
            name='reff',
            field=models.CharField(default=1596030332227, max_length=200),
        ),
        migrations.AlterField(
            model_name='specimendata',
            name='temperature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='specimendata',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
