# Generated by Django 2.2.12 on 2020-07-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20200729_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimendata',
            name='reff',
            field=models.CharField(default=1596043867655, max_length=200),
        ),
    ]
